export const developerProfile = {
  name: "Christopher Appiah-Thompson",
  appStoreUrl: "https://apps.apple.com/us/developer/christopher-appiah-thompson/id1887579155?uo=4",
  website: "https://worldclassscholars.vercel.app",
};

export const appleApps = [
  {
    slug: "agedcare-monitor",
    name: "AgedCare Monitor",
    bundleId: "wcs.Agedcare-shared",
    category: "Medical",
    price: "Free",
    releaseDate: "2026-05-23",
    appStoreUrl: "https://apps.apple.com/us/app/agedcare-monitor/id6767978725?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/47/25/63/47256317-38da-982e-7089-a7755c697226/AppIcon-0-0-1x_U007emarketing-0-8-0-85-220.png/512x512bb.jpg",
    audience: "Professional carers, family carers, and aged-care facility staff",
    headline: "Non-clinical monitoring support for aged-care teams.",
    summary:
      "A privacy-minded monitoring aid for resident safety workflows, incident review, carer dashboards, and Apple Watch alert support.",
    highlights: ["Fall and distress-sound monitoring aid", "Resident timeline and staff dashboard", "Apple Watch alert companion"],
  },
  {
    slug: "ai-real-investor",
    name: "AI Real Investor",
    bundleId: "wcs.AI-Real-Investor",
    category: "Finance",
    price: "$3.99",
    releaseDate: "2026-06-17",
    appStoreUrl: "https://apps.apple.com/us/app/ai-real-investor/id6779068906?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/49/21/1d/49211d29-e411-8329-a998-6f1f04c5dd83/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Property investors and finance decision-makers",
    headline: "Property and investment decision-support workspace.",
    summary:
      "A premium workspace for reviewing property signals, investment considerations, and decision-support outputs before acting.",
    highlights: ["Property investment review", "Decision-support workflow", "Premium finance workspace"],
  },
  {
    slug: "carelens-aged",
    name: "CareLens Aged+",
    bundleId: "wcs.Carelens-Aged-",
    category: "Medical",
    price: "$7.99",
    releaseDate: "2026-06-08",
    appStoreUrl: "https://apps.apple.com/us/app/carelens-aged/id6767072418?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/65/00/17/65001740-baaa-f2b0-d936-63af36925ac0/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Clinicians, facility managers, and aged-care teams",
    headline: "Intelligent aged-care coordination and insight support.",
    summary:
      "Designed for teams working with ageing, dementia, care planning, and resident-support workflows.",
    highlights: ["Care planning support", "Aged-care insight workspace", "Professional team focus"],
  },
  {
    slug: "legalaid",
    name: "LegalAid",
    bundleId: "wcs.LegalAid",
    category: "Productivity",
    price: "$0.49",
    releaseDate: "2026-06-26",
    appStoreUrl: "https://apps.apple.com/us/app/legalaid/id6782532109?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/00/a2/6f/00a26fcb-947a-5c2b-bc7d-032ebacd99f8/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "People and legal professionals preparing legal-information workflows",
    headline: "Legal-information workflows, document review, and draft reports.",
    summary:
      "Structure legal facts, review pasted document text, identify risk signals, prepare jurisdiction-aware prompts, and generate draft reports for qualified review.",
    highlights: ["Document understanding", "Jurisdiction-aware prompts", "Draft reports for review"],
  },
  {
    slug: "peacelens",
    name: "PeaceLens",
    bundleId: "wcs.PeaceLens",
    category: "Education",
    price: "$3.99",
    releaseDate: "2026-06-09",
    appStoreUrl: "https://apps.apple.com/us/app/peacelens/id6776995376?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/62/f1/01/62f10117-eb93-0f0e-dcc4-03a9caf27e69/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Researchers, journalists, election observers, trainers, and policy teams",
    headline: "Peace journalism analysis for election-related media.",
    summary:
      "Capture media reports, score coverage with an explainable Peace Journalism Index, compare findings, and prepare research outputs.",
    highlights: ["Peace Journalism Index", "Election media coding", "Research export workflow"],
  },
  {
    slug: "prop-valulator",
    name: "Prop-Valulator",
    bundleId: "wcs.Prop-Valulator",
    category: "Lifestyle",
    price: "$0.49",
    releaseDate: "2026-06-17",
    appStoreUrl: "https://apps.apple.com/us/app/prop-valulator/id6780286834?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/97/c4/ee/97c4ee87-5fa8-650a-d60f-7e794380ca4c/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Homeowners, property watchers, and valuation explorers",
    headline: "AI-assisted property valuation exploration.",
    summary:
      "Explore property value signals with AI-powered graph inference and heuristic valuation support.",
    highlights: ["Property signal review", "AI-assisted valuation", "Scenario exploration"],
  },
  {
    slug: "psychologic",
    name: "PsychoLogic",
    bundleId: "wcs.PsychoLogic",
    category: "Medical",
    price: "$7.99",
    releaseDate: "2026-06-22",
    appStoreUrl: "https://apps.apple.com/us/app/psychologic/id6778269526?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/11/79/73/117973b1-dc85-c2d1-d53f-6f824d853ae0/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Journal users and reflective wellbeing workflows",
    headline: "Private journaling for everyday thoughts, feelings, and patterns.",
    summary:
      "A general-purpose journal for recording experiences and reflecting on patterns without replacing professional care.",
    highlights: ["Private reflective journaling", "Pattern awareness", "General wellbeing support"],
  },
  {
    slug: "psychosocial-analytics",
    name: "Psychosocial Analytics",
    bundleId: "wcs.Psychosocial--Analytics",
    category: "Medical",
    price: "$14.99",
    releaseDate: "2026-06-01",
    appStoreUrl: "https://apps.apple.com/us/app/psychosocial-analytics/id6768490648?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/10/71/89/107189f0-48ac-636e-5944-2d24bfce9596/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Social workers and clinical teams",
    headline: "Structured psychosocial assessment and reporting support.",
    summary:
      "Capture structured psychosocial information, organize analysis, and support professional documentation workflows.",
    highlights: ["Structured capture", "Clinical-team workflow", "Report-ready outputs"],
  },
  {
    slug: "truthlens-global",
    name: "TruthLens Global",
    bundleId: "wcs.TruthLens",
    category: "News",
    price: "$9.99",
    releaseDate: "2026-06-08",
    appStoreUrl: "https://apps.apple.com/us/app/truthlens-global/id6776208825?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/26/2d/fd/262dfd09-dba1-7347-89fc-1cb06e4df670/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Readers, civic teams, educators, and public-interest reviewers",
    headline: "Review public claims before you share, repeat, or act.",
    summary:
      "Scan civic messages, speeches, social posts, and public-interest claims with verdicts, confidence, bias signals, and source credibility.",
    highlights: ["Claim review support", "Bias and credibility signals", "Offline fallback heuristics"],
  },
  {
    slug: "visionforge",
    name: "VisionForge",
    bundleId: "wcs.VisionForge",
    category: "Graphics & Design",
    price: "$5.99",
    releaseDate: "2026-06-11",
    appStoreUrl: "https://apps.apple.com/us/app/visionforge/id6777670360?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/15/33/4b/15334b12-841d-4750-9b53-154057662b78/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Creators, designers, and prompt-driven visual explorers",
    headline: "Creative AI generation workspace.",
    summary:
      "Explore text-to-image and visual generation workflows in a focused creative design environment.",
    highlights: ["Text-to-image exploration", "Creative prompt workspace", "Design ideation"],
  },
  {
    slug: "wcs-agentic",
    name: "WCS Agentic",
    bundleId: "wcs.WCS-Agentic",
    category: "Business",
    price: "Free",
    releaseDate: "2026-06-24",
    appStoreUrl: "https://apps.apple.com/us/app/wcs-agentic/id6769985809?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/a4/03/89/a4038925-593e-8233-e40c-3f16b648233b/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "World Class Scholars leaders and administrators",
    headline: "Scholar programs, agent commands, approval gates, and reporting.",
    summary:
      "Manage scholar operations, supervised finance AI reporting, compliance tasks, and human approval controls in one mobile workspace.",
    highlights: ["Program oversight", "Governed agent activity", "Board-ready finance briefs"],
  },
  {
    slug: "wcs-geo",
    name: "WCS-GEO",
    bundleId: "wcs.WCS-GEO",
    category: "Business",
    price: "$9.99",
    releaseDate: "2026-06-17",
    appStoreUrl: "https://apps.apple.com/us/app/wcs-geo/id6777616166?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/d7/c0/d5/d7c0d5bd-1602-56a2-2b0c-a7b0f0ec8456/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Geologists, students, educators, consultants, investors, and exploration professionals",
    headline: "Mineral exploration learning and demonstration tool.",
    summary:
      "Explore explainable target scoring, project maps, ranked mineral targets, evidence provenance, imports, sync demos, and field observations.",
    highlights: ["Explainable target scoring", "Project maps and layers", "Field observation workflows"],
  },
  {
    slug: "wcs-pol",
    name: "WCS-POL",
    bundleId: "wcs.WCS-POL",
    category: "Education",
    price: "$0.49",
    releaseDate: "2026-06-17",
    appStoreUrl: "https://apps.apple.com/us/app/wcs-pol/id6779397120?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/b9/ad/40/b9ad401f-96b2-b1e5-cb3e-f550d63a3c0f/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Civic educators, students, and governance learners",
    headline: "Electoral governance simulation and institutional learning.",
    summary:
      "Explore how institutional rules, civic choices, and governance dynamics shape electoral outcomes.",
    highlights: ["Governance simulation", "Civic learning", "Institutional scenarios"],
  },
  {
    slug: "wcs-tatto",
    name: "WCS-Tatto",
    bundleId: "wcs.WCS-Tattoo-Studio",
    category: "Lifestyle",
    price: "$2.99",
    releaseDate: "2026-06-06",
    appStoreUrl: "https://apps.apple.com/us/app/wcs-tatto/id6774959552?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/36/a6/a6/36a6a647-18ef-8d68-6c25-d94748cc3d25/AppIcon-0-0-1x_U007emarketing-0-5-85-220.png/512x512bb.jpg",
    audience: "Tattoo clients, artists, and studios",
    headline: "Premium tattoo planning built on trust and compassion.",
    summary:
      "Plan tattoo ideas, studio conversations, style direction, and client-centred preparation.",
    highlights: ["Tattoo planning", "Style direction", "Studio conversation support"],
  },
  {
    slug: "wcslib",
    name: "WCSLIB",
    bundleId: "wcs.WCSLIB",
    category: "Education",
    price: "$3.99",
    releaseDate: "2026-06-05",
    appStoreUrl: "https://apps.apple.com/us/app/wcslib/id6764653278?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/f7/44/b1/f744b1a4-dffa-e504-4b3c-d34d353a228c/AppIcon-0-0-1x_U007epad-0-1-85-220.png/512x512bb.jpg",
    audience: "Students, researchers, and lifelong learners",
    headline: "Scholarly workspace for learning and research.",
    summary:
      "A focused educational workspace for organizing scholarly exploration, public resources, and lifelong learning.",
    highlights: ["Scholarly workspace", "Research organization", "Learning support"],
  },
  {
    slug: "wendy-safricanfash",
    name: "Wendy'SAfricanFash",
    bundleId: "wcs.AfricanFashionApp",
    category: "Shopping",
    price: "Free",
    releaseDate: "2026-06-19",
    appStoreUrl: "https://apps.apple.com/us/app/wendysafricanfash/id6763326670?uo=4",
    artworkUrl: "https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/0c/5e/ec/0c5eec30-a25f-0636-cf88-91584383e756/AppIcon-0-0-1x_U007emarketing-0-8-0-85-220.png/512x512bb.jpg",
    audience: "African fashion shoppers, designers, and marketplace visitors",
    headline: "Premium African fashion marketplace and design support.",
    summary:
      "Discover African fashion collections, marketplace experiences, and AI-assisted design workflows.",
    highlights: ["African fashion marketplace", "Design inspiration", "Shopping experience"],
  },
];

export const appleAppCategories = [...new Set(appleApps.map((app) => app.category))].sort();

export const appleLaunchStats = {
  totalApps: appleApps.length,
  freeApps: appleApps.filter((app) => app.price === "Free").length,
  paidApps: appleApps.filter((app) => app.price !== "Free").length,
  categories: appleAppCategories.length,
};
